name = "rl_vac"
uuid = "46ddd8e2-534b-4823-9286-76d8df98e7f1"
authors = ["SAUL DIAZ INFANTE VELASCO <sauld@cimat.mx> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11.1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
